### ISSUE TITLE
NewPlugin: VSXquery

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#10]
Query VSX for star [roperties, populate Phase dialog with Period/Epoch

plugin/src/org/aavso/tools/vstar/external/plugin/VSXquery.java
plugin/build.xml

**Comment by dbenn** [comment]
I'm guessing that at least one use case for this is for when data was not loaded from AID (which also loads data from VSX for the Info dialog) but you want info on the target from VSX.

**Comment by mpyat2** [comment]
Exactly.

**Comment by dbenn** [comment]
Duplicate of #30
