### ISSUE TITLE
Replace .vstar file with Java Preferences API internally?

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#104]
Sometimes, the VStar window will start as minimised to the point where almost nothing of it can be seen but the upper left part of the title bar. 

Paul York most recently reported this. Peter Brack saw this during the 2018 VStar CHOICE course.

See also https://sourceforge.net/p/vstar/bugs-and-features/626/

If the .vstar file does not exist, VStar should create it at startup.

A related problem is that the .vstar file (in user's home directory) is not always updated with the latest window position and size. 

A solution to all of this may be to use the Java Preferences API instead of a separate .vstar file:
~~~
cat ~/.vstar
#VStar user properties. Read on startup, written on exit.
#Thu Dec 31 13:05:30 ACDT 2020
main_wdw_width=1059
main_wdw_height=766
main_wdw_upper_left_y=56
main_wdw_upper_left_x=244
~~~

**Comment by mpyat2** [comment]
@dbenn : I played with it (Java Preferences API instead of .vstar file in ApplicationProperties.java).
All is OK except Java Web Start: the sandboxed application does not have access to Java Preferences API.

**Comment by dbenn** [comment]
Thanks @mpyat2. At some point will need to decide whether to abandon webstart.

**Comment by mpyat2** [comment]
Hi @dbenn ,
I've pushed a new branch issue-104-vstar-file-to-prefAPI (I have not created a pull request yet).
Could you please take a look at it? I've changed ApplicationProperties.java so it uses Java Preferences API now.
If Java Preferences API is not accessible (Java Web Start) the program window will take some reasonable size (~80% screen size/height).
The minimum size is restricted to 800x600 (the user can make the program window smaller yet restored values will not be less than 800x600).

**Comment by dbenn** [comment]
Looks good @mpyat2 !

**Comment by dbenn** [comment]
Thanks Max
