### ISSUE TITLE
Allow user-defined ordering of series on plot or at least make Filtered series last to render

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#108]
Hans-Georg writes on the AAVSO VStar forum:

> In VStar, if I use "View > Simple filter": ObsCode equal to <myObsCode>, I can mark my own observations with the "Filtered" color. In the Preferences (Series Size) I set the size of (e.g. VIS, Johnson V ...) to a value greater than that for "Filtered". So I can see my own observations with a (smaller) blueish dot in front of the original observation. So far so good. But for Cousins R the Filtered dot is BEHIND the observation point, so you don't see it.

This is a pre-defined ordering. It's a good point though. Filtered observations should be in front I suppose, i.e. the last to be rendered. Or the rendering should be user definable.

**Comment by mpyat2** [comment]
See #125
"Invert Series Order?" checkbox in PlotControlDialog gives the _partial_ solution. Sometimes it may be sufficient.

**Comment by dbenn** [comment]
It seems reasonable to close this with the partial fix. If we want a more customisable solution in future, we can create another issue.
