### ISSUE TITLE
Developing VStar plugins doc needs updating

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#110]
Paul York has found some broken links and the possible need to update text in the Developing VStar plugins doc.

**Comment by dbenn** [comment]
https://github.com/AAVSO/VStar/blob/issue-105-function-application/plugin/doc/vstar_plugin_dev.odt

**Comment by yorkpf** [comment]
I think there are 3 steps to this:
1.  Move the inline code to GitHub; Make any minor / cosmetic changes to the document.
2. Put this document back into circulation (it is now accurate and useable, as far as we know).
3. Later on, as I work through the pieces of ex-inline code (presumably stored elsewhere on GitHub), I can make any required changes in situ.

I have downloaded the .odt document to my desktop and have made a couple of cosmetic changes on page 3, using Word. How do I upload this and get it back into circulation (steps 1 and 2 are now complete, thanks to you)?

I simply clicked on the downloaded file and it came up in Word. Presumably, I just save it as a .odt file? Are there any problems with using Word for this purpose?

Maybe you can tell me how best to go about step 3?

Paul

**Comment by dbenn** [comment]
Thanks @yorkpf. I'd be happy to chat about committing changes via git. That would be a good first foray into this.

One thing I've been wondering about for awhile is making more use of the GitHub wiki for such documents. Slightly different to plugin docs themselves, since they need to match particular versions of code.

But I think, let's get the changes committed to git first and then we can make that decision later.

**Comment by dbenn** [comment]
@yorkpf committed line spacing changes to the document: https://github.com/AAVSO/VStar/commit/cf9203ac60801995707d61aa6a0fc72579319528

**Comment by dbenn** [comment]
I'll close this issue and we can reconsider use of wiki in future.
