### ISSUE TITLE
Flexible Text Format plugin: multispace separator

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#114]
Make a new kind of separator: 'multispace'.
It should allow reading files where columns separated by several spaces, treated as a single separator.
An example: extracting a non-default aperture (MAG_0) from ASAS-3 datafile.

Example of ASAS-3 data (note leading spaces and that MER_2 column separated by several spaces):
```
#     HJD      MAG_2  MAG_0  MAG_1  MAG_3  MAG_4    MER_2 MER_0 MER_1 MER_3 MER_4 GRADE FRAME
   2707.90366 10.305 10.290 10.309 10.298 10.307    0.037 0.038 0.037 0.046 0.054  A 44322
   2710.90509 10.306 10.240 10.320 10.313 10.310    0.027 0.033 0.029 0.031 0.037  A 44865
   2721.87613 10.261 10.259 10.252 10.261 10.268    0.034 0.038 0.034 0.042 0.049  A 46584
```

Flexible Text File directives to put at the beginning of the file:
```
#DELIM=multispace
#FIELDS=,TIME,,MAG,,,,,MAGERR
#DATE=HJD
#DATEADD=2450000
#FILTER=ASAS-3 (mag_0)
#DEFINESERIES=ASAS-3 (mag_0),ASAS-3 (mag_0),#000000
#VELAFILTER=magnitude<11 and magnitude>10.15
```

Leading spaces are interpreted as a separator too, so TIME is the second column (see #FIELDS)

**Comment by clkotnik** [comment]
This seems like a nice enhancement.  Do you think there is a need for some way to specify an empty item?

**Comment by mpyat2** [comment]
> 
> 
> This seems like a nice enhancement. Do you think there is a need for some way to specify an empty item?

Hm... I think empty items are possible only if columns have fixed widths. If they are separated by the different number of spaces, empty items are not allowed...
