### ISSUE TITLE
JFreeChart library update

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#117]
VStar uses JFreeChart version 1.0.13, dated 20 Apr 2009. An update to the most recent version 1.5.2 (31 Dec 2020) is proposed.

**Comment by dbenn** [comment]
I notice that 2.0.0 is in the works (https://github.com/jfree/jfreechart) but there may be more compatibility issues here. I note that pseudo 3D plots have gone away and they defer to Orson Plots for 3D (http://www.object-refinery.com/orsoncharts/).

**Comment by mpyat2** [comment]
I compiled jfreechart-1.6.0-SNAPSHOT.jar (from code https://github.com/jfree/jfreechart) using maven. It requires JDK 11 to compile. I see API changes: getXYPlot method does not exist anymore. So the transition to JFreeChart >1.5 is problematic.

**Comment by dbenn** [comment]
Looks like something to keep an eye on for the future then eh? 1.5 seems like the way to go. Perhaps that could be tied to the next increase in minimum JRE version for VStar. We're currently being fairly modest in our requirements.

There may be other libs whose version could be increased. Apache Commons Math, for example. Last time I looked though, going up a major version entailed significant changes. Another issue entirely.

**Comment by dbenn** [comment]
Hi @mpyat2, where are we at with this one? Was there a pull request?

**Comment by mpyat2** [comment]
Hi @dbenn , 
There was no pull request.
If you don't mind replacing the library with a newer version, I'll create the pull request.

**Comment by mpyat2** [comment]
On the other hand, there were some changes involving charting. Probably I'll try to create a new branch based on the current master.

**Comment by dbenn** [comment]
Hi Max

Given that it’s a very specific replacement with no overlaps, plese feel free to make the change on master and don’t worry about the PR.

David

**Comment by dbenn** [comment]
Oh, in that case, please feel free to do it all on a branch with a PR. :)
