### ISSUE TITLE
Common VELA filter does not work in KeplerFITSObservationSource

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#12]
### Common VELA filter does not work in KeplerFITSObservationSource 

**reason**: missing constructor of class KeplerFITSObservationRetriever
**should be**:
~~~
public KeplerFITSObservationRetriever {
    super(getVelaFilterStr());
}
~~~
From https://sourceforge.net/p/vstar/bugs-and-features/708/ by @mpyat2

**Comment by mpyat2** [comment]
@dbenn: already fixed, can be closed
