### ISSUE TITLE
Unit Tests for Plugins

### ISSUE THREAD

**Issue by yorkpf** [AAVSO/VStar#120]
Plugins deserve to have their own unit tests, as currently exist for core code. Especially for Observation Source Plugins, rather than test these manually. Some plugins have existing UTs, but only a minority.

**Comment by dbenn** [comment]
One approach here is to add the infrastructure in the class that sits at the base of all plugins via JUnit's test case, requiring only a test method to be implemented. A default no-op implementation of the test method could be created for backward compatibility. Forcing it to be implemented would mean the developer makes a deliberate choice not implement anything but an empty test though.

**Comment by dbenn** [comment]
The AoV plugin would be a good first candidate to try this on, especially since a design-for-test would require test code to bypass UI code while testing the key parts of the plugin code. It would also more easily give us confidence that a multi-core version still worked as expected.

**Comment by dbenn** [comment]
The base class of all plugins should have a `Test` method that returns either `null`, `true` or `false` or an `Optional<Boolean>` to indicate that there is no test, the test passed, or the test failed. From a purely intentional and slightly aesthetic viewpoint, I favour `Optional<Boolean>` since it connotes a freedom to choose whether or not to write a test.

**Comment by dbenn** [comment]
Further, we will add a unit test whose job it is to load each plugin, invoke its test method, and report the result of each non-null/optional test.

**Comment by dbenn** [comment]
Okay, plugin unit test workflow is working now. Had to recall what the issue was from #6 and also pay a bit more attention to the exception in the GitHub action log.

**Comment by dbenn** [comment]
Further to the last comment, as per commits, there was a bit more to be done.

What we now have is a generalised, separate test runner for currently installed plugins. This is useful during development as well as in GitHub actions.

The way it works is that a plugin developer can opt to write a test by overriding the `test()` method in a plugin and all such tests will be for internal plugins and and any that can be installed via `plugin/build.xml`'s test target (`ant test` in `plugin` directory). An overall pass/fail and individual report of tests is given on `stdout`. If not overridden, the `test()` method returns `null` signalling to the `PluginTest` test runner class that there is no test for that plugin. Otherwise, true or false is returned to denote pass/fail.

@mpyat2 I'd be interested in your thoughts on all of this. My aim here is to make writing plugin tests more integral to the plugin development process while adding minimal overhead to each plugin.

**Comment by dbenn** [comment]
See here for an example:

https://github.com/AAVSO/VStar/blob/issues-120-UTs-for-plugins/plugin/src/org/aavso/tools/vstar/external/plugin/ASASObservationSource.java#L259

I've only implemented two plugin tests so far @mpyat2: AAVSO Upload Format and ASAS

**Comment by dbenn** [comment]
I think of this as being a bit like Design For Test, a hardware design & verification trend that came to prominence a couple of decades ago.

**Comment by dbenn** [comment]
This approach also allows white-box testing since the `test()` method can see everything the rest of the plug-in's code can see.

**Comment by dbenn** [comment]
Here's the output from the test right now:
~~~
    [junit] Running org.aavso.tools.vstar.external.plugin.PluginTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec
    [junit] Output:
    [junit] Running 43 Plugin Tests...
    [junit] [NO TEST] VeLaFilterPlugin ('Uses VeLa to permit arbitrarily complex observation filters.')
    [junit] [NO TEST] JulianDateObservationsFilter ('Filter for Julian Date Observations')
    [junit] [PASSED]  ObserverListFilter ('Filter for list of Observers') test
    [junit] [NO TEST] VSXquery ('VSX Query')
    [junit] [NO TEST] MeanTimeBetweenSelectionTool ('Accumulates selected observations and calculates mean time between selections')
    [junit] [NO TEST] JDToDateTool ('Convert JD to Calendar Date')
    [junit] [NO TEST] CurrentModeANOVATool ('Compute ANOVA for current plot mode's mean series')
    [junit] [NO TEST] ApacheCommonsPolynomialFitCreatorPlugin ('Polynomial Fit')
    [junit] [NO TEST] VeLaModelCreator ('VeLa model creator')
    [junit] [NO TEST] ApacheCommonsLoessFitter ('Loess Fit')
    [junit] [NO TEST] FourierModelCreator ('Create a Fourier model independent of period search')
    [junit] [NO TEST] SimpleFormatObservationSinkPlugin ('Save as simple text format file.')
    [junit] [NO TEST] DownloadFormatObservationSinkPlugin ('Save as AAVSO download format file.')
    [junit] [NO TEST] AIDWebServiceCSV2ObservationSourcePlugin ('AAVSO International Database observation source')
    [junit] [NO TEST] TextFormatObservationSourcePlugin ('Observation source for AAVSO download and simple formats')
    [junit] [NO TEST] SuperWASPFITSObservationSource ('SuperWASP file v2 observation reader')
    [junit] [NO TEST] DASCHObservationSource ('DASCH file reader')
    [junit] [NO TEST] FlexibleTextFileFormatObservationSource ('Flexible Text File Format Reader')
    [junit] [NO TEST] GAIADR2XformObSource ('Gaia DR2 Photometry Format reader')
    [junit] [NO TEST] KeplerFITSObservationSource ('Kepler/TESS FITS file v2.2 observation source')
    [junit] [PASSED]  ASASObservationSource ('ASAS file reader') test
    [junit] [NO TEST] ASASSNObservationSource ('ASAS-SN CSV file reader')
    [junit] [NO TEST] QLPFITSObservationSource ('QLP FITS file v0.2 observation source')
    [junit] [NO TEST] LightKurveFITSObservationSource ('Lightkurve output observation source v0.2')
    [junit] [NO TEST] CatalinaSkySurveyObservationSource ('Catalina Sky Survey file reader')
    [junit] [NO TEST] BMinusVObservationSource ('B-V series creator')
    [junit] [NO TEST] HipparcosObservationSource ('Hipparcos file reader')
    [junit] [PASSED]  AAVSOUploadFileFormatObservationSource ('AAVSO Upload File (Visual and Extended) Format reader') test
    [junit] [NO TEST] APASSEpochPhotometryObservationSource ('APASS epoch photometry observation source plug-in.')
    [junit] [NO TEST] NSVSObservationSource ('NSVS file reader')
    [junit] [NO TEST] AAVSOnetEpochPhotometryObservationSource ('AAVSOnet epoch photometry observation source plug-in.')
    [junit] [NO TEST] ObserversBySeries ('Observation tool plug-in to display observers by series')
    [junit] [NO TEST] DescStatsBySeries ('Observation tool plug-in to display descriptive statistics by series')
    [junit] [NO TEST] PeriodLuminosityDistanceCalculator ('Leavitt's Law (Period-Luminosity Relationship) distance calculator')
    [junit] [NO TEST] HJDConverter ('Heliocentric JD Converter')
    [junit] [NO TEST] MagnitudeBaselineShifter ('Magnitude Baseline Shifter')
    [junit] [NO TEST] VeLaObservationTransformer ('VeLa observation transformation tool')
    [junit] [NO TEST] DcDftStandardScanPeriodAnalysisPlugin ('Date Compensated Discrete Fourier Transform Standard Scan')
    [junit] [NO TEST] DcDftFrequencyRangePeriodAnalysisPlugin ('Date Compensated Discrete Fourier Transform with Frequency Range')
    [junit] [NO TEST] DcDftPeriodRangePeriodAnalysisPlugin ('Date Compensated Discrete Fourier Transform with Period Range')
    [junit] [NO TEST] WeightedWaveletZTransformWithFrequencyRangePlugin ('Weighted Wavelet Z-Transform time-frequency analysis')
    [junit] [NO TEST] WeightedWaveletZTransformWithPeriodRangePlugin ('Weighted Wavelet Z-Transform time-period analysis')
    [junit] [NO TEST] AoVPeriodSearch ('AoV period search')
    [junit] ** PASSED: 3, FAILED: 0, NO TEST: 40
~~~
3 passing tests, only 40 tests to write! :) Of course, some plug-ins won't really need tests. I'm writing tests for as many plug-ins as I can right now to get an idea of how general the framework is.

**Comment by dbenn** [comment]
See https://github.com/actions/setup-java for multiple Java GitHub actions YAML
