### ISSUE TITLE
VeLa: trouble with a signed positive exponent

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#138]
From Max in email:

VeLa has troubles with a signed positive exponent.

You can check this with `Tools`->`VeLa`. 

Try entering `3.5754842e+18` and run the interpreter. You will see `20.718281828459` as a result! 

Without the `+` sign, all is OK: `3575484200000000000`.

**Comment by dbenn** [comment]
One approach here is to intercept this before VeLa sees it via regex and change the string. I'd rather fix it via ANTLR4 though.

**Comment by dbenn** [comment]
I'm actually thinking that there's no real need for E+nn in a real number when Enn can be used.

I've tried reworking the VeLa grammar to handle E+ but there's some issue I'm not seeing. There's only one unit test in `VeLaTest` affected by this and there's no real need for E+, as indicated.

**Comment by dbenn** [comment]
I'm actually thinking that there's no real need for E+nn in a real number when Enn can be used.

I've tried reworking the VeLa grammar to handle E+ but there's some issue I'm not seeing. There's only one unit test in `VeLaTest` affected by this and there's no real need for E+, as indicated.

**Comment by mpyat2** [comment]
@dbenn , I agree. There is no need to implement it. Currently, format procedures generates numbers without +
