### ISSUE TITLE
Install/Update All buttons in plugin manager

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#155]

**Comment by dbenn** [comment]
@mpyat2 @SaraAAVSO I've taken the approach of removing the Delete All button, adding an All? checkbox which applies to Install, Update and Delete buttons.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/4115628/118273930-adc79680-b503-11eb-9908-89272936b9cc.png">

**Comment by mpyat2** [comment]
Thank you, @dbenn 
I'm looking at it and will add a couple of minor changes.

**Comment by dbenn** [comment]
If you are happy with my last minor commit @mpyat2, and if we think we are done with UI changes, I'll merge the branch and update the user manual.

The Install and Update buttons have the same effect when All? is selected. We could hide the Update button in all-mode, but I'm not sure whether to be concerned about that. Thoughts?

**Comment by mpyat2** [comment]
I think all is ok, see also my comment to #155.
