### ISSUE TITLE
File Open dialogue not showing Directory List correctly

### ISSUE THREAD

**Issue by yorkpf** [AAVSO/VStar#180]
When I attempt to open the attached ASAS-SN file (3rd attachment) using the ASAS-SN plugin in version 2.21.3 of VStar, the attached screen appears (1st attachment) - it shows no files at all in my Documents folder, even though the file to be loaded actually resides there.

What it should be showing is as per the 2nd attachment from the previous version 2.21.2 of VStar which operates correctly.

![Screen Shot 2021-07-09 at 3 03 37 pm](https://user-images.githubusercontent.com/76934896/125145660-7d981f00-e165-11eb-9a5e-e7a494db7944.png)

![Screen Shot 2021-07-09 at 3 07 05 pm](https://user-images.githubusercontent.com/76934896/125145704-a6201900-e165-11eb-8f39-9a23914af28b.png)

[light_curve_9fdbe5a6-3dfc-4800-b47f-c9719326b76b.csv](https://github.com/AAVSO/VStar/files/6794338/light_curve_9fdbe5a6-3dfc-4800-b47f-c9719326b76b.csv)

**Comment by dbenn** [comment]
This is a strange one. Just checking that it's the same Documents folder in both cases @yorkpf? The only reason I ask is that with Apple Cloud there can be more than one and I've found it easy to get confused.

**Comment by yorkpf** [comment]
Hi David. 

Just checked it. It (VStar 2.21.3) is still behaving in the same weird way (2.21.2 is OK).

Your idea is interesting re the Apple Cloud. My Documents folder which contains most of my operational data is backed up on the Cloud, but however I approach it, via the Finder, it appears to contain all my sub-folders (as in the 2.21.2 case).

Can you think of any way to test your idea a bit further?

Regards
Paul

**Comment by dbenn** [comment]
Hi @yorkpf, perhaps it's not that at all. I will see if I can think of other ways to test this. One idea I'm wondering about is whether to point people on the VStar forum to this issue and ask whether others have experienced this problem.

What version of Mac OS X do you have? Java version?

I have Mac OS X Catalina 10.15.4 and currently Corretto Java 11:
~~~
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
~~~

**Comment by yorkpf** [comment]
I have macOS Big Sur, version 11.6

No idea of the Java versions and can’t recall how to find out …

**Comment by dbenn** [comment]
Thanks Paul. The easiest way is to open the Terminal application and type:
~~~
java -version
~~~
and take a screenshot or copy & paste the output. Don't stress too much over it though.

**Comment by yorkpf** [comment]
David

java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)
(base) ***@***.*** ~ % 

Paul

**Comment by dbenn** [comment]
Jim Bedient has experienced a similar problem:

  https://www.aavso.org/comment/160428#comment-160428

with Java 8 update 311, VStar (2.21.3), Mac OS X Catalina V 10.15.7

**Comment by dbenn** [comment]
Hi @yorkpf  As a matter of interest, when you look in that same folder we see nothing in, but via another application, e.g. Word, does the listing look normal there?

**Comment by yorkpf** [comment]
Yes, the “Documents” directory shows up properly in Word, for example and also the Finder.
Paul

**Comment by mpyat2** [comment]
Hi @dbenn, under Ubuntu, I saw some inconsistent behavior of the Open dialog (other problem than in this issue); the problem was gone when I changed window manager. It's impossible in MaxOS; however, why not try Java Swing's default look and feel to see what happens? I could make a little change in the code: add a command-line option '--default_look_and_feel' with subsequent changes of VStar.java (only several lines need to be changed).

**Comment by dbenn** [comment]
Great idea @mpyat2. Could well be related and may be a good workaround.

**Comment by mpyat2** [comment]
Ok, I'll create the issue and branch

**Comment by mpyat2** [comment]
See #274

**Comment by dbenn** [comment]
One other thing we could consider in future is adding this as a Preference.

**Comment by dbenn** [comment]
In discussion with @yorkpf recently, we agreed that this is being caused by a "feature" of Mac OS X that allows one to inadvertently or otherwise deny access to part of one's own file system. See for example this page for access change: https://support.apple.com/en-au/guide/mac-help/mchlp1203/mac

Not a VStar problem.
