### ISSUE TITLE
In QLPFITSObservationSource plug-in: fractional part of reference time should be read via BJDREFR keyword

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#181]
Currently, fractinal part of BJD reference time is read using BJDREFF keyword, like in Kepler/TESS plug-in.
However, the correct QLP keyword is BJDREFR.
It seems that this keyword is always = 0
BJDREFR =                  0.0 / fraction of the day in BJD reference date      

However, the code need to be fixed for consistency,

**Comment by dbenn** [comment]
Thanks Max.

**Comment by mpyat2** [comment]
Thank you, David!
