### ISSUE TITLE
Allow more harmonics in Fourier models periods dialog

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#183]
I've had this request a few times and again recently.

List, combobox or free form entry?

**Comment by mpyat2** [comment]
Hi David @dbenn 

It would be useful. Right now I am working with an eclipsing variable for which 12 harmonics is not enough so I made a special build with max=16 harmonics.

in HarmonicInputDialog.java: "private int getMaxHarmonicsForFreq(double freq)": maxHarmonics can be increased, maximum value is 25, limited by dmat[][] in TSBase.java.

Combobox is ok I think

Cheers,
Max

**Comment by dbenn** [comment]
Hi @mpyat2, I've made the maximum 25. That would seem to be a reasonable maximum. I've tested it on a Cepheid up to 21 and the residuals look good. Of course, may just be fitting the noise in some cases.

That Fortran to Java port I did in the TSBase code has arrays with elements from 0..51. The 1 is because I was just going with the 1-based Fortran arrays, sacrificing the zeroth element, to simplify the port. Lots of improvements that could be made in that code, as you've no doubt seen. When I originally ported this and the WWZ code, I didn't have a lot of time leading up to the 2nd Citizen Sky workshop and wanted to get feedback from Grant Foster and others there. I guess the key thing is that it works reasonably well at this point.

Wondering whether we can push the max to 50 rather than 25 though?

**Comment by mpyat2** [comment]
Well, if the algorithm works as expected, there is no problem with one extra element. I think 25 harmonics is ok. It should be enough for most cases where the light curve is more or less smooth; if it contains "breaks" (like this: https://www.aavso.org/vsx_docs/2224765/3633/PhasePlot20210927.png ) the algorithm does not give a satisfactory approximation anyway.
