### ISSUE TITLE
Implement filter name changes determined by HQ

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#203]
George Silvis reminded me that:

> VSD will soon report Rc data as R, Ic as I and Z as SZ. 
> It will still honor requests by the old names, but report with the new.

VStar needs to accommodate this.

**Comment by dbenn** [comment]
Hi @SaraAAVSO. George Silvis reminded me that this was coming. Can you let me know when the time is right to support this?

**Comment by SaraAAVSO** [comment]
Hi @dbenn,
I don't think VStar needs to change at all.
VStar doesn't use the VSD database, does it? 
It only uses aid.observations and it uses the band number then converts that to the long name of the band (not the abbreviation). The long names of the bands (i.e. Johnson V, Sloan Z, etc.) did not change.
Out of curiosity, does VStar use the aid.bands table to get those names? If it does, then absolutely nothing will have to change.
Thanks, Sara

**Comment by dbenn** [comment]
Okay, very good, better still @SaraAAVSO 

I thought these changes went beyond VSD. Good that they don't.

I get the current bands from https://www.aavso.org/vsx/index.php?view=api.bands and generate Java enum code when there's an advertised change with this script: https://github.com/AAVSO/VStar/blob/master/script/gen_bands_enums_from_ws.py

Have considered automating this for some time but given the number of times these change, not really worth it. Also, VStar is not always talking to the network to get band info, often opening files. Could do this as "sneaky reads", but again, may not really be worth doing so.

I just checked the bands against what VStar has and there are no changes, so therefore, closing this issue.

Thanks.
