### ISSUE TITLE
Mediator requestRA/requestDec: min/max input boundaries

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#210]
Min/Max values in requestRA(), requestDec() methods (Mediator.java) should be corrected.

requestRA(): 
hours: 0 - 23 **(now 0 - 60)**
minutes: 0 - 59 (now 0 - 60)
Seconds: can be left as is (0 - 60) or set to 0 - 59.999

requestDec():
(arc)minutes: 0-59 (now 0-60)
(arc)seconds : can be left as is (0 - 60) or set to 0 - 59.999

decHours in requestDec should be named decDegrees.

Also, it would be useful to check resulted DecInfo. For example, if degrees=90 and minutes > 0, we will get DecInfo.degs > 90.

**Comment by dbenn** [comment]
Seems reasonable, but shouldn't requestRA() have hours in range 0 - 24 in this case?

**Comment by mpyat2** [comment]
Hi @dbenn ,

Well, RA is defined in a range 0..360 degrees, not including 360 (360 is equivalent to 0). Similarly, in hours RA >= 0 and < 24h.
See, for example, https://www.swift.psu.edu/secure/toop/convert.htm

Of course, we could ignore limits, so the result can be >360 (or even <0 if negative values allowed) and then normalize the result to 0 .. <360 range (to avoid possible problems with input arguments of other methods) yet it is not intuitive and confusing.

**Comment by dbenn** [comment]
Hi @mpyat2, okay understand that 0 <= RA < 360 and likewise 0 <= RA_hours < 24, so yep, ignore my comment.

**Comment by mpyat2** [comment]
See also #75

**Comment by dbenn** [comment]
Close this one now?

**Comment by mpyat2** [comment]
yes, please!
