### ISSUE TITLE
VSX Query: rounding issues of sexagesimal RA/Dec

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#212]
Sometimes J2000 fields can show 60.00 sec in RA or 60.0 arcsec in Dec. 
This happens if seconds >59.995 or arcsec > 59.95

In such a case, seconds should be 0 with incrementing minutes (and sometimes hours / degrees)

![image](https://user-images.githubusercontent.com/44919945/146945530-6f8950f7-4763-43d3-8f66-8c04e0b0c5e3.png)

**Comment by mpyat2** [comment]
Solved, see #213

**Comment by dbenn** [comment]
Can we close this one since the PR is merged or more to be done?

**Comment by mpyat2** [comment]
yes, please close it!
