### ISSUE TITLE
AoV AssertionError if code executed from within Eclipse

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#214]
If assertions enabled, AccertionError generated while clicking plot or table of AoV result.

![image](https://user-images.githubusercontent.com/44919945/147359214-5e9257d7-5725-49a4-a053-e79179d9dbd8.png)

See PeriodAnalysisDataPoint.java: getFrequency(), getPeriod(), getPower(), getAmplitude().
coordTypes does not equal to DCDFT_COORD_TYPES if the first constructor PeriodAnalysisDataPoint is called directly (as AoV plug-in does). Internal DC DFT plug-ins call the second constructor, so the assertions do not throw exceptions (coordTypes does equal to DCDFT_COORD_TYPES).

I do not understand the logic of such check yet.

**Comment by dbenn** [comment]
Wow, thanks for picking this one up Max. I'll sort this out. The assertions are historic leftovers. I'll cast an eye over that code in general while I'm there.

Hope you are had a good day yesterday, in whatever way you celebrate (or don't). :)

**Comment by dbenn** [comment]
These assertions in getter methods are historical and make no sense for other plugins such as AoV or indeed anything that is not DCDFT. I'm puzzled re: why they exist. For any given plugin, we can't guarantee any particular coordinate types, except perhaps frequency and period. If any such assertions are ever used now, they should be present in the main constructor.
