### ISSUE TITLE
Create ZTF plugin

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#220]
It's probably worth creating ZTF (https://www.ztf.caltech.edu/) plug-in.
Data format: comma-separated or tab-separated from ZTF site https://irsa.ipac.caltech.edu/cgi-bin/Gator/nph-dd?catalog=ztf_objects_dr8&mode=html&passproj&
or the same tab-separated format from VSX (example: https://irsa.ipac.caltech.edu/cgi-bin/ZTF/nph_light_curves?POS=CIRCLE%20308.47287%2059.94742%200.0004&FORMAT=HTML)

**Comment by dbenn** [comment]
Sounds good to me Max.
