### ISSUE TITLE
VeLa observation source plug-in

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#221]
Currently, VeLa Model Plug-in builds models bound to existing observation points. Sometimes it is useful to have a possibility of building a 'quasi-continuous' model that is independent of existing observations (similarly to plotModel.R / VStarModelPlot)

This can be done with a kind of observation plug-in.

See pictures:

![image](https://user-images.githubusercontent.com/44919945/147557316-4b072607-fd97-40df-ac6e-2a8c49e763ef.png)

![image](https://user-images.githubusercontent.com/44919945/147557210-80490de7-1921-48c3-93fd-dc66e2039fe9.png)

**Comment by mpyat2** [comment]
@dbenn , what do you think about it? I already made the prototype.

**Comment by dbenn** [comment]
That is very cool @mpyat2! I love the idea. Nice. Yes, please go ahead. This also makes it easier for a CHOICE course instructor to create a simple data set for analysis for period analysis.

**Comment by dbenn** [comment]
We could omit the text "observation source" and simply have: `New Star from VeLa Model...` in the menu.

**Comment by mpyat2** [comment]
Plug-in preview:
https://youtu.be/WWYJdAvRcTU

Side effects:
* new class import org.aavso.tools.vstar.ui.dialog.FileIOchoosers.java has been created
* an object of class FileIOchoosers created in Mediator.java, so small changes were made in Mediator class.

Issues:
In WebStart mode, loading/saving model files is currently impossible (**the same issue exists in VeLa model plug-in!**)

**Comment by dbenn** [comment]
That is very cool. Thanks!

Yes, the WebStart issue... Does pasting VeLa code into the window work?

**Comment by mpyat2** [comment]
Unfortunately, pasting does not work too (for both my plug-in and VeLa Model).

**Comment by dbenn** [comment]
I think that's consistent with all WebStart plugins in VStar, IIRC.

**Comment by dbenn** [comment]
Thanks Max!
