### ISSUE TITLE
VeLaModelCreator should apply NumericPrecisionPrefs.formatTime() on model function's time parameter

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#223]
`VeLaModelCreator`'s `VeLaUnivariateRealFunction.value()` method should invoke `NumericPrecisionPrefs.formatTime()` on the model function's time parameter.

This came from a discussion with @mpyat2 in email in which he noticed the lack of localisation, for which VeLa expression evaluation was defined.

**Comment by dbenn** [comment]
What do you think about doing this @mpyat2?

**Comment by mpyat2** [comment]
Agreed!
