### ISSUE TITLE
Toolbar buttons / menu items remain disabled if a file obs. plug-in has param dialog that canceled

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#224]
1. Load any light curve (for example, New Star from AAVSO database->R Lyr->OK)
2. New Star from File -> ASAS-SN -> select (any) file -> press [Cancel] in [parameters] dialog.
3. Most of toolbar buttons remain disabled (along with corresponding menu items)

However, if you try New Star from AAVSO database and press [Cancel], all items get enabled again.

**Comment by dbenn** [comment]
Yes, I have seen this behaviour before and should've opened an issue. Thanks.
