### ISSUE TITLE
Fix unit tests for Java versions > 8

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#236]
There has apparently been a regression on master since all VStar UTs > Java version 8 are failing.

There's also an issue with the Ant UT target in the presence of an Eclipse build that attempts to run additional tests in the `build` directory.

**Comment by dbenn** [comment]
See also #229

**Comment by dbenn** [comment]
All VeLa unit tests are now passing except for the locales "nn" (Norwegian Nynorsk) and "ar_JO" (Arabic Jordan) for which `testNegExponent()` fails.

We could open an issue to address these as a background task or go further now. There are plenty of other issues to work on so spending undue time on this right now may not be prudent. Thoughts @mpyat2?

**Comment by mpyat2** [comment]
> All VeLa unit tests are now passing except for the locales "nn" (Norwegian Nynorsk) and "ar_JO" (Arabic Jordan) for which `testNegExponent()` fails.
> 
> We could open an issue to address these as a background task or investigate further now. There are plenty of other issues to work on so spending undue time on this right now may not be prudent. Thoughts @mpyat2?

I agree.

**Comment by mpyat2** [comment]
@dbenn , 
Norwegian Nynorsk case can be easily fixed: they use U+2212 (−) instead of a hyphen. This case can be easily fixed by adding a line
```
dfs.setMinusSign('-');
```
into ExpressionVisitor.ParseDouble().

ar_JO case is more complicated and can be investigated later.

**Comment by dbenn** [comment]
Awesome. Thanks Max. I've committed a fix for this.

**Comment by mpyat2** [comment]
@dbenn , thank you!
