### ISSUE TITLE
B-V observation source plugin creates observations with no names

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#246]
This prevents AAVSO download format files containing just B-V from loading. Take name from B or V ob.

Also, as a fall-back, have AAVSO download format sink plugin set name to `Unknown` if null or `""`.

**Comment by dbenn** [comment]
https://www.aavso.org/comment/161889#comment-161889, the forum comment that indirectly led to this issue being created, raised the question of whether other fields should be added to B-V observations, such as Transformed, comparison star fields, CMag, KMag, charts etc? Clearly comparison star fields, CMag, KMag are problematic because they are specific to the original B and V observations. The time value is the mean of the B and V observation times, for example. The magnitude is of course B-V and no uncertainty is recorded. I suppose that mean uncertainty could be used, but what does this really mean? These are after all, synthetic observations.

**Comment by mpyat2** [comment]
the resulted uncertainty could be = sqrt(unsert_B^2 + uncertA^2), if I correctly recall the rules for uncertainties of combined values. This must be checked though.

**Comment by dbenn** [comment]
Okay, yes, probably better than mean error. :) Do you recall the CHOICE course, uncertainty about uncertainty, several years ago. Barbara Harris ran it but I don't think it ran more than once or twice. Perhaps we could ask Brad Walter, or consult CCD/DSLR manuals?

**Comment by mpyat2** [comment]
Unfortunately, I have not participated in that CHOICE course, it is a rudimental memory from my first year at the University, laboratory work :)

**Comment by dbenn** [comment]
Yes, I recalled having seen that elsewhere when you mentioned it as well, other than AAVSO. :)
