### ISSUE TITLE
Model interpolation between observations

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#257]
One way to approach this is to have linear interpolation between model data points. This can be done in the same way as is done now for periodogram plots. At one point this was in place for all models but there were problems getting this working in phase plots, in particular for both previous and standard phase plots.

Another is to increase the resolution of model output by additional applications of the model function between observations. Residuals could not meaningfully be created from these extra data points however.

**Comment by mpyat2** [comment]
plus extrapolation
