### ISSUE TITLE
Some preferences are not read/saved in WebStart mode

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#280]
In WebStart mode, some preferences (i.e. series size/color, locale) are not read nor saved.

**Comment by dbenn** [comment]
As you say, if we are moving away from WebStart, a fix for this is less important, but people will still use WebStart for some time, so fixing this is a Good Thing in the short term.

**Comment by dbenn** [comment]
Hi @mpyat2. I have not yet tested this via WebStart (which we are planning to move away from now) but I suspect you have. Happy to close this issue when you are.

**Comment by mpyat2** [comment]
Yes, please close it, @dbenn !
