### ISSUE TITLE
Performance problems with large (~100K obs) datasets with many series

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#291]
e.g. load last two years of SS Cyg data with all bands selected.

Raised in recent CHOICE course: https://www.aavso.org/comment/162798#comment-162798

Leo said there:

> Like Ron, I have some questions about performance.  Are the times I am experiencing normal, or am I doing something wrong?
> 
>     Initial load of SS Cyg (all bands): 55 secs
>     Deselect Johnson V on the Plot Control dialog: 5 secs
>     Select all bands on the Plot Control dialog: 3 mins 4 secs
>     Deselect all bands on the Plot Control: 6 mins
>     Select discrepant: 15 secs

**Comment by dbenn** [comment]
Profiling with VisualVM is revealing that insofar as the `Select All` bands problem is concerned, the `include()` method in the `VisualSeriesRowFilter` class is the problem, from lines 102 or 103 onward. The `SeriesType`related for loop was a relatively recent addition and it is the `equals()` method in `SeriesType` and `ValidObservation` that are taking all the time.

<img width="650" alt="Screen Shot 2022-06-17 at 22 34 21" src="https://user-images.githubusercontent.com/4115628/174303885-21a8bc4b-3da0-4fdd-9473-c902dc753bd5.png">

**Comment by dbenn** [comment]
Two approaches initially suggest themselves:
- disable/remove `VisualSeriesRowFilter` until after series selection operation completes.
- optimise the `include()` method.

**Comment by dbenn** [comment]
Looking at the CHOICE course comments (from Leo and Ron), the time blowout is primarily with select/deselect all in the plot control dialog. The O(N) line mentioned in the comment above must only be called to check whether an observation exists in some other series not yet checked. The only such series would be user defined series. Therefore, adding a guard to check for whether a visible series type is user defined would make sense.

**Comment by dbenn** [comment]
Another thing that would help is for all occurrences of `List<ValidObservation>` were `LinkedHashSet<ValidObservation>` since insertion order is preserved but lookup is O(1) instead of O(N). This is where C/C++ typedefs would be handy in Java.

**Comment by dbenn** [comment]
Having a set of series (or better yet, series other than that given by getBand()) to which an observation belongs in `ValidObservation` would allow an O(1) test of whether an observation belonged to another series, such as filtered or user defined.

**Comment by dbenn** [comment]
Another thing to note is that I see that even with the current release (2.22.0), the current (and slow) technique for checking whether an observation belongs to another series (user defined) does not have the desired effect on the observation list pane anyway!

**Comment by dbenn** [comment]
@mpyat2 I have committed a fix for this (see last two commits above) but annoyingly, I have committed all this to the `master` branch! Apologies.

Would you mind looking at what I've committed and let me know if you have questions?

The key changes are to `VisibleSeriesRowFilter` and `ValidObservationTableModel` to properly handle user defined observations. In support of this, there is also a new field in `ValidObservation` to allow an observation's band to be distinguished from series, in the case of copied, user-defined observations.

**Comment by dbenn** [comment]
@mpyat2, this seems to be working as expected; have you seen any problems? Unfortunately because I accidentally committed to master, the only way to see the changes is to look at the 2 commits (see above).

**Comment by mpyat2** [comment]
Hi @dbenn , sorry for the late answer.
I have seen problems so far, I think the issue can be marked as solved.

**Comment by dbenn** [comment]
Closing

**Comment by dbenn** [comment]
Marking as fixed
