### ISSUE TITLE
Time axis tick labels switch to scientific notation with enough zoom

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#293]
See https://www.aavso.org/comment/162855#comment-162855 from @BradWalter

**Comment by mpyat2** [comment]
Technically, it is possible to set a user-defined formatter for the axis, i.e. in the AbstractObservationPlotPane constructor:
```
		NumberAxis domainAxis = (NumberAxis) chart.getXYPlot().getDomainAxis();
		domainAxis.setNumberFormatOverride(myFormatter);
```

This will prevent an automatic switch to scientific notation.

However, the number of decimal digits will change depending on zoom even if a user-defined formatter is set.

From my point of view, the current behavior is acceptable; in my tests, the switch occurs when Tmax - T min < 0.001 (approximately).

**Comment by dbenn** [comment]
Thanks for your analysis and suggested fix @mpyat2. I tend to agree with your conclusion.

The alternatives seem to be:
- implement the fix you have proposed, or
- mark this with a `wontfix` label and close.

I suspect you would recommend the second option? At the very least, this is a low priority.

**Comment by mpyat2** [comment]
Hi @dbenn ,
I think the second option is better. The 'fix' I proposed is rather a concept; the axis with a user-defined format I've tried looked more 'ugly' than the original. It seems we must implement too many tiny things to make the fix appropriate.
