### ISSUE TITLE
Change link to user manual from Help menu

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#298]
`MenuBar.java:createHelpContentsListener()` opens a browser to:
  https://www.aavso.org/sites/default/files//vstar/VStarUserManual.pdf
~~~
/**
* Returns the action listener to be invoked for Help->User Manual Online...
*/
public ActionListener createHelpContentsListener() {
  return new ActionListener() {
	public void actionPerformed(ActionEvent e) {
	  openHelpURLInWebBrowser("https://www.aavso.org/files/vstar/VStarUserManual.pdf");
	}
  };
}
~~~
This needs to be changed to:
  https://github.com/AAVSO/VStar/blob/master/doc/user_manual/VStarUserManual.pdf

**Comment by dbenn** [comment]
Another approach here now that we don't support WebStart, the Help Contents menu item could open the local file in a browser via a `file://` URL in the installed files or just open the PDF as a file, but that assumes a PDF viewer like Preview (Mac), Acrobat (Windows).

**Comment by mpyat2** [comment]
>but that assumes a PDF viewer like Preview (Mac), Acrobat (Windows).

Modern browsers (Firefox, Chrome, MS Edge) at least under Windows have a built-in pdf reader (see picture). So in most cases, the user does not need additional PDF software.


![image](https://user-images.githubusercontent.com/44919945/183288345-fc327481-2940-4351-b0bc-600f70e921eb.png)

**Comment by dbenn** [comment]
Absolutely true @mpyat2. It was the last part of that comment: "...or just open the PDF as a file, but that assumes a PDF viewer like Preview (Mac), Acrobat (Windows)" rather than the part about using `file://` that made me wonder about the need for standalone applications.

**Comment by mpyat2** [comment]
Oh, indeed, I've missed it. Sorry, @dbenn

**Comment by dbenn** [comment]
The location of the VStar User Manual PDF may vary in location locally depending upon whether it's a Mac, Windows, or Linux distribution. Indeed, there is no guarantee that we will be able to know for sure where the PDF ends up (e.g. a Mac DMG's content can be separated so that docs and example files end up being separated).

The end result we want here is to be able to make life easier for HQ (Sara, Bert), not having to place files on a HQ server for us. One idea I've had is to create a (maybe sticky) VStar forum where the latest user manual goes. This could have all user manual versions or just the latest. The URL would be easily constructed from the version number and known attachment URL.

As an additional level of indirection, a persistent URL could be updated to allow us to put the PDF anywhere on the web. VStar would always simply use that URL. The only problem is that may not be seen as a PDF file (e.g. if a bit.ly link). So, perhaps the AAVSO VStar forum attachment approach is OK.

We can always try a few things like this to see how it all goes.

Thoughts welcome as always.

**Comment by dbenn** [comment]
Oh... Just remembered that forum posts (outside of CHOICE courses) don't allow attachments currently...

**Comment by dbenn** [comment]
In email, @SaraAAVSO said:

> ...if AAVSO HQ has to update the link to the Manual for the webpage whenever there is a new release, that isn't really much of a hardship - just about any of us could do it.

So, this should be considered a low priority issue and possibly closed.

**Comment by dbenn** [comment]
Closing, given the foregoing.

**Comment by dbenn** [comment]
Changing close status since we are essentially saying this won't be fixed.

**Comment by dbenn** [comment]
Changing close status since we are essentially saying this won't be fixed.

**Comment by dbenn** [comment]
Changing close status since we are essentially saying this won't be fixed.

**Comment by dbenn** [comment]
Changing close status since we are essentially saying this won't be fixed.

**Comment by dbenn** [comment]
@mpyat2, I'm just putting the change log together and looking at this again. To me, given that the user manual ink on https://www.aavso.org/vstar has changed to https://github.com/AAVSO/VStar/blob/master/doc/user_manual/VStarUserManual.pdf rather than a special HQ location, I think the menu bar Help menu item in VStar should too.

What do you think?

**Comment by dbenn** [comment]
If you agree, I'll do this on the branch I already have for #366.

**Comment by mpyat2** [comment]
> If you agree, I'll do this on the branch I already have for #366.

Hi @dbenn , I agree!

**Comment by dbenn** [comment]
Closed, fixed as per comments and branch above.
