### ISSUE TITLE
Create an installation recipe for Mac and Linux on wiki

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#302]
Create an installation recipe for Mac and Linux here: https://github.com/AAVSO/VStar/wiki/Installation-Recipes

Prompted by https://www.aavso.org/node/89476

**Comment by dbenn** [comment]
Added sections to https://github.com/AAVSO/VStar/blob/master/ReadMe.md re: OS specific installation.

**Comment by dbenn** [comment]
I've added more sections to https://github.com/AAVSO/VStar/wiki/Installation-Recipes for Mac OS X, Linux (and bash) as well as command-line options and TOC links to other sections.

**Comment by dbenn** [comment]
@mpyat2 can you have a look at the new sections I've added? I'll also ask Tom C to do so since he made the request.

**Comment by mpyat2** [comment]
Hi @dbenn , I looked at the "How to install VStar under Mac OS X" section. No comments from my side; it looks pretty normal.

**Comment by dbenn** [comment]
Thanks @mpyat2. I made a few changes in the Mac and bash sections. See also https://www.aavso.org/linuxmac-isntallation#comment-164212

**Comment by dbenn** [comment]
Asked for input from Tom Calderwood who initially prompted me to add the Linux and Mac sections via https://www.aavso.org/node/89476
