### ISSUE TITLE
VStar cannot load saved 'Residials'

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#310]
1) Create any model, go to the 'Residuals' tab and save the dataset using default Type='Download', Delimiter='Comma'
2) Try to open the saved file using the default 'Download or Simple' source. An error "Required index >=0" occurs.
![image](https://user-images.githubusercontent.com/44919945/210166524-8f797d57-25d4-45ba-935e-6c6195eef137.png)

There is something wrong with the standard 'Residuals' series. If you replace 'Residuals' with another name in the file (for example, 'Residuals1') the file gets loaded (as 'Unspecified')

**Comment by dbenn** [comment]
This is reminiscent of another problem we saw awhile ago where the name was missing in obs.

Was the name you added in each row or via a #NAME directive?

**Comment by mpyat2** [comment]
It's not a star name, is a series 'filter' name. I renamed 'Residuals' to Residuals1 by the 'replace all' command in a text editor for each line.

**Comment by dbenn** [comment]
Very odd. Trying to debug.
