### ISSUE TITLE
VStar should quote the "comments" field while saving .csv data

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#311]
The "Comments" field may contain commas. Currently, VStar saves comma-separated (.csv) data without taking it into account.
Try to load V405 Dra light curve (Johnson V filter, All times) and save observations into a .csv file. Opening the file via the default "Download or Simple" source gives no data (No observations found). This is because VStar gets confused with commas inside the "Comments" field. The solution is enclosing the "Comments" into double quotes (taking care of possible existing quotes inside the field!)

**Comment by dbenn** [comment]
Good pick-up. Surprised this has not been found before. Thanks Max.
