### ISSUE TITLE
The Gaia DR2 photometry plugin currently does not work because of web-service unavailability

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#332]
It seems that the Gaia DR2 photometry web service is not available now.
The Gaia DR2 photometry plugin gives the error:
![image](https://user-images.githubusercontent.com/44919945/220978588-1db38d72-1227-4b7b-8a49-f429710076a4.png)

**Comment by dbenn** [comment]
I've sent an email to the contact email address at Gaia:

  https://gaia.ari.uni-heidelberg.de

giving this as an example request:

  http://geadata.esac.esa.int/data-server/data?RETRIEVAL_TYPE=epoch_photometry&FORMAT=CSV&ID=3105860283909081728

**Comment by dbenn** [comment]
A reply to that email asked me to submit a ticket via https://www.cosmos.esa.int/web/gaia/gaia-helpdesk, so I did. The response to that ticket (GXZ-202-84598was:

> Dear David,
> 
> Thanks for your interest in the Gaia DR3 data. 
> 
> Please update the previous url by changing "geadata" to "gea":
> 
> http://geadata.esac.esa.int/data-server/data?RETRIEVAL_TYPE=epoch_photometry&amp;FORMAT=CSV&amp;ID=3105860283909081728 &gt;&gt; http://gea.esac.esa.int/data-server/data?RETRIEVAL_TYPE=epoch_photometry&amp;FORMAT=CSV&amp;ID=3105860283909081728
> 
> For more information about the programmatic access to the DataLink products please have a look at the "DataLink: Command access"tutorial available at: https://www.cosmos.esa.int/web/gaia-users/archive/programmatic-access#CommandLine_DataLink
> 
> Regards,
> Héctor

**Comment by dbenn** [comment]
Changed URL as per ticket. Testing.

**Comment by dbenn** [comment]
This kind of problem is also an argument for plugin preferences.

**Comment by dbenn** [comment]
Currently see 404 error from:
~~~
http://gea.esac.esa.int/data-server/data?RETRIEVAL_TYPE=epoch_photometry&FORMAT=CSV&ID=3105860283909081728 
~~~
So too for:
~~~
https://gea.esac.esa.int/data-server/data?RETRIEVAL_TYPE=epoch_photometry&RELEASE=Gaia+DR2&FORMAT=CSV&ID=3105860283909081728
~~~
and
~~~
https://gea.esac.esa.int/data-server/data?RETRIEVAL_TYPE=epoch_photometry&RELEASE=Gaia+DR3&FORMAT=CSV&ID=3105860283909081728
~~~

**Comment by dbenn** [comment]
This DR2 example from the plugin header fails in the same way, with or without `RELEASE=Gaia+DR2` added:
~~~
https://gea.esac.esa.int/data-server/data?RETRIEVAL_TYPE=epoch_photometry&FORMAT=CSV&RELEASE=Gaia+DR2&ID=4116592768715278848
~~~

**Comment by dbenn** [comment]
Okay, this was complicated by the fact that the service was down for awhile while I was testing (confirmed via Gaia ticket).

The initial advice to change geadata to gea was insufficient. Also had to change http to https.

**Comment by dbenn** [comment]
Tested with two Gaia IDs: 3105860283909081728, 5912901375001820288

**Comment by dbenn** [comment]
Would also be good to be able to load a Gaia file.
