### ISSUE TITLE
Only one data element expected in AID CSV data stream

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#36]
I see this error:

> Only one data element expected in AID CSV data stream

<img width="459" alt="image" src="https://user-images.githubusercontent.com/4115628/85934092-4e798b80-b91d-11ea-91ad-8490004177ed.png">

when attempting to load HIP105217 from AID.

After seeing @clkotnik's post:

  https://www.aavso.org/help-identifying-variable-type

I was curious to look at the data and also to see whether there was any AID data as well as TESS. There probably isn't (I have not checked VSX) but it's immaterial for the bug at hand.

I have not seen this error before.

**Comment by gregorydonohue** [comment]
Ran into the same error for V457 Lac.  (Using VStar 2.21.2.)

**Comment by dbenn** [comment]
Thanks for the additional example @gregorydonohue
