### ISSUE TITLE
Updates for 2.23.0 release

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#366]
- VeLa.g4 comment removals with issues created
- version change
- user manual check and revision table
- remove deprecated applet UI class to avoid build warnings, especially since applets are not "a thing" now
- add CFF file
- change user manual link (see #298)
- update About box
- Change log

**Comment by dbenn** [comment]
@mpyat2, go to [this branch](https://github.com/AAVSO/VStar/tree/366-updates-for-2230-release-version-user-manual) and note the addition of a citation item:

<img width="370" alt="image" src="https://github.com/AAVSO/VStar/assets/4115628/b9505e6c-b3f4-420e-ad31-550cd1821658">

**Comment by mpyat2** [comment]
Ok, got it

**Comment by mpyat2** [comment]
Hi @dbenn ,

Imagine someone wanting to cite VStar using BibTex format.

Would it be correct (a .bib file entry):

```
@misc{benn23,
        author = {{Benn}, David and
                  {Beck}, Sara and
                  {Pyatnytskyy}, Maksym and
                  {Kotnik}, Cliff and
                  {Lee}, Sam and
                  {Weber}, Adam and
                  {Dadighat}, Michelle and
                  {Camargo}, Nico},
        title = {AAVSO VStar},
        year = {2023},
        abstract = {VStar is a multi-platform, free, open source application
                    for visualizing and analyzing time-series data. It is
                    primarily intended for use with variable star
                    observations, permitting light curves and phase plots to
                    be created, viewed in tabular form, filtered, and
                    analyzed. Period search, model creation, and
                    time-frequency analysis are supported. Data can be loaded
                    from the AAVSO International Database and various other
                    sources. VStar's feature set can be expanded via plug-ins,
                    for example, to read Kepler or Gaia mission data.},
        URL = {https://www.aavso.org/vstar},
        keywords = {variable stars, period search, period analysis, time-frequency analysis,
                    discrete Fourier transform, weighted wavelet z-transform,
                    Fourier models,
                    polynomial fits,
                    plug-in,
                    light curve,
                    phase plot},
        note = {license AGPL-3.0}
}
```
This gives something like this (this is an AAS example with the AASTeX style):
![image](https://github.com/AAVSO/VStar/assets/44919945/e804f0d0-b715-403d-ab20-a07e9651cbdf)

**Comment by dbenn** [comment]
What I see from the GitHub citation in BibTex format is:
~~~
@software{Benn_VStar,
author = {Benn, David and Beck, Sara and Pyatnytskyy, Maksym and Kotnik, Cliff and Lee, Sam and Weber, Adam and Dadighat, Michelle and Camargo, Nico},
license = {AGPL-3.0},
title = {{VStar}},
url = {https://github.com/AAVSO/VStar}
}
~~~
and for APA format I see:
~~~
Benn, D., Beck, S., Pyatnytskyy, M., Kotnik, C., Lee, S., Weber, A., Dadighat, M., & Camargo, N. VStar [Computer software]. https://github.com/AAVSO/VStar
~~~
So, those are different from what you show above.

**Comment by mpyat2** [comment]
I've just tried your example. Essentially, it gives the same result (with the latest AASTeX v6.3.1 style [note that this style is recommended by JAAVSO: https://www.aavso.org/jaavso-information-authors])
However, it seems that the 'year' entry is required, if the 'year' is not defined, we have got '????' in the citation text.

**Comment by dbenn** [comment]
Thanks for picking this up Max. I should have noticed.

There's a `date-released` field (YYYY-MM-DD format) in CFF and others can be added, such as `version`. I've just added/committed that.

I think `date-released` will work, because they give an example like that here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by mpyat2** [comment]
@dbenn , 
Shame on me. When I read the first comment (about citation prompt) I completely missed it (the citation prompt itself) and made the bibtex variant manually. Indeed, the Citation prompt creates it automatically. Oops... Probably the sun overheated me today :)

**Comment by dbenn** [comment]
No worries Max. :)

**Comment by dbenn** [comment]
The auto-generated output includes the date now, which it didn't before the last change.
~~~
Benn, D., Beck, S., Pyatnytskyy, M., Kotnik, C., Lee, S., Weber, A., Dadighat, M., & Camargo, N. (2023). VStar (Version 2.23.0) [Computer software]. https://github.com/AAVSO/VStar 

@software{Benn_VStar_2023,
author = {Benn, David and Beck, Sara and Pyatnytskyy, Maksym and Kotnik, Cliff and Lee, Sam and Weber, Adam and Dadighat, Michelle and Camargo, Nico},
license = {AGPL-3.0},
month = aug,
title = {{VStar}},
url = {https://github.com/AAVSO/VStar},
version = {2.23.0},
year = {2023}
~~~
