### ISSUE TITLE
PluginManager cannot correctly check for local and remote plug-in equality

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#373]
It is supposed that PlugInManager enables the Update button for a particular plug-in only if the local and remote copies are non-equal.
The problem is in getBytesFromURL() method: it was supposed that stream.available() returns the stream length. This is actually not the case: "Note that while some implementations of InputStream will return the total number of bytes in the stream, many will not. It is never correct to use the return value of this method to allocate a buffer intended to hold all data in this stream" (see the Java documentation).

It **does** work if the remote path is a local directory and **sometimes** works for Web (for instance for my test website http://mpta.atwebpages.com/vstar/plugins/ ; even for this site sometimes it returns 0) but does NOT work for www.aavso.org.

I'm sure we can fix the issue (it is not critical anyway, rather 'cosmetic'). But, @dbenn , do we really need to load the plug-ins from a remote location? Probably, for Linux users, it would be helpful. If yes, we could simplify PluginManages, leaving a single [Install/Update] button instead of the two ones. Anyway, we rely on the plug-in equality solely without checking what is newer.

**Comment by dbenn** [comment]
@mpyat2, does "do we really need to load the plug-ins from a remote location" relate to #192?

As you go on to say:
> ...we could simplify PluginManages, leaving a single [Install/Update] button instead of the two
we could just unconditionally install whether or not it's changed, as you say.
