### ISSUE TITLE
VSX error when getting info for R Car

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#377]
This URL:

  https://www.aavso.org/vsx/index.php?view=api.object&ident=R+Car&data=0

gives a response for both R Car and r Car:
~~~
<?xml version="1.0" encoding="UTF-8"?>
<VSXObject>
    <Name>R Car</Name>
    <AUID>000-BBQ-500</AUID>
    <RA2000>143.06083</RA2000>
    <Declination2000>-62.78889</Declination2000>
    <ProperMotionRA>-36.2200</ProperMotionRA>
    <ProperMotionDec>17.7400</ProperMotionDec>
    <VariabilityType>M</VariabilityType>
    <Period>307.0</Period>
    <Epoch>2454597</Epoch>
    <RiseDuration>48</RiseDuration>
    <MaxMag>3.9 V</MaxMag>
    <MinMag>10.5 V</MinMag>
    <SpectralType>M4e-M8e</SpectralType>
    <Discoverer>Benjamin Gould (1871)</Discoverer>
    <Category>Variable</Category>
    <OID>5754</OID>
    <Constellation>Car</Constellation>
    <Data>
        <Count>29236</Count>
    </Data>
</VSXObject>
<VSXObject>
    <Name>r Car</Name>
    <AUID>000-BBR-533</AUID>
    <RA2000>158.89708</RA2000>
    <Declination2000>-57.55764</Declination2000>
    <ProperMotionRA>-15.9300</ProperMotionRA>
    <ProperMotionDec>0.4900</ProperMotionDec>
    <VariabilityType>LB</VariabilityType>
    <MaxMag>4.44 V</MaxMag>
    <MinMag>4.47 V</MinMag>
    <SpectralType>K3/4II</SpectralType>
    <Category>Variable</Category>
    <OID>43528</OID>
    <Constellation>Car</Constellation>
    <Data>
        <Count>0</Count>
    </Data>
</VSXObject>
~~~
There should be only one unique result.

@bpablo-aavso or @aru-py, any thoughts on this?

**Comment by mpyat2** [comment]
Confirmed with the VSQquery plug-in: the similar error 
Execution Exception: 
The markup in the document following the root element must be well-formed.

**Comment by dbenn** [comment]
Note that the following search via the VSX web page also returns these two results:

https://www.aavso.org/vsx/index.php?view=results.submit0

Either this is a recent change in VSX behaviour or r Car (vs R Car) is a recent addition. The lack of discernment between lower and uppercase r and R seems new though.

**Comment by dbenn** [comment]
Discussed with Patrick Wils and Sebastien Otero who determined it to be an issue relating to a duplicate name recently entered in VSX. This has been resolved with any code changes required in VStar or the VSX API.
