### ISSUE TITLE
Basic 'help' functionality for plug-ins

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#379]
Implementation of the basic help functionality for plug-ins.

See the branch 'plugin-manager-help-functionality'

1) New getDocName() method in IPlugin
3) If getDocName() is implemented in the plug-in, it must return the name of the pdf document.
2) 'Help' button in the plugin manager dialog:
![image](https://github.com/AAVSO/VStar/assets/44919945/a6d5a892-d918-468f-a272-6b8481610491)

**Comment by dbenn** [comment]
Yep, I like it.  Have thought about this too.

This would supplement browsing the wiki, e.g. https://github.com/AAVSO/VStar/wiki/Observation-Source-Plug%E2%80%90ins

A modified approach would be to add a link to the wiki section, but a PDF makes as much sense as anything. The wiki may be quicker to load is one upside and a brief description may be all someone wants initially. Reminds me I need to link all PDFs in the wiki plugin pages. Happy to go with your approach though.

**Comment by dbenn** [comment]
Further to my last comment, rather than the name of the PDF that VStar adds a URL base prefix to, I'm thinking that it should always a full URL that's specified since then someone can write a plugin and point to the wiki or somewhere else if they wish.

Perhaps a compromise could be that the plugin logic says:
- if docSpecifier starts with "http", use that
- else add base URL prefix to docSpecifier

Thoughts?

**Comment by mpyat2** [comment]
Hi @dbenn ,
I've implemented the following approach:
1) the plugin document  name can be a file name (without path) resided in the base plug-in doc directory (in this case it may contain spaces and other special characters).
2) Or it can be a full document URL (in this case, spaces and special characters must be properly encoded (i.e. %20 instead of space))

Now, every plug-in returns the pdf file name if it exists in the document repository or the full URL targeting Wiki.
PluginManagementDialog interprets it accordingly.

**Comment by mpyat2** [comment]
Hi @dbenn ,

I've moved the HTML help call to Mediator as a static method. This allows us to use the help functionality in the plug-in dialogs.
See the ZTF observation source as an example. Not all plug-ins have a dialog, however, so for them, currently, the only place to invoke help is PluginManagerDialog.

![image](https://github.com/AAVSO/VStar/assets/44919945/fb385c40-c950-4625-adbb-9a66efef7c13)

Cheers,
Max

**Comment by mpyat2** [comment]
Thank you, @dbenn !
