### ISSUE TITLE
The Harmonics dialog is displayed twice

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#382]
1. Do "DC DFT"
2. Select a point
3. Press the "Find Harmonics" button.

The "Harmonics" dialog is displayed. Press Dismiss. The same dialog will be displayed one more time.

**Comment by mpyat2** [comment]
see also https://github.com/AAVSO/VStar/issues/61#issuecomment-720451600

**Comment by mpyat2** [comment]
see the branch '[period-analysis-messages](https://github.com/AAVSO/VStar/tree/period-analysis-messages)'

**Comment by dbenn** [comment]
I have definitely seen this bug before. Thanks.

**Comment by mpyat2** [comment]
I address this bug in #383, too.
