### ISSUE TITLE
Change authentication URL to copy-to-clipboard button

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#402]
The authentication dialog would be more user friendly and compact if a `Copy URL` button was added instead of requiring the user to copy the URL text explicitly.

**Comment by mpyat2** [comment]
Yes, it would be helpful. I used the similar approach in ZTF and Gaia dialogs:
![image](https://github.com/AAVSO/VStar/assets/44919945/ece12632-5470-4557-b5cd-f5fc4d713252)

**Comment by dbenn** [comment]
Thanks @mpyat2! I have a copy to clipboard button in the Log dialog as well.
