### ISSUE TITLE
VSXQuery plugin extension: star's vicinity image, SIMBAD link

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#412]
Some 'toy' extensions to VSXQuery: an image of the star's vicinity (like in VSX) and a link to SIMBAD.
![image](https://github.com/AAVSO/VStar/assets/44919945/8d0ca286-49a9-45ed-bda3-8754fe14f27a)

**Comment by dbenn** [comment]
More than toy extensions. Very cool @mpyat2
