### ISSUE TITLE
FlexibleTextFormatObservationSink refactoring

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#420]
Removing code duplication

**Comment by mpyat2** [comment]
Solved

**Comment by dbenn** [comment]
Out of curiosity, was this solved as part of another issue?

**Comment by mpyat2** [comment]
Well, I see "quoteForCSVifNeeded" was moved to ValidObservation as a static method in branch "issue-420-flexibletextformatobservationsink-refactor".

**Comment by dbenn** [comment]
Thanks, I recall now!
