### ISSUE TITLE
TextFormatObservationSourcePlugin hides exception

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#424]
While trying to read the attached file using the "Download or Simple" observation source, nothing happens; even an error message is not shown. Actually, an exception occurs in the analyser.analyse() in TextFormatObservationSourcePlugin.java, yet it is hidden.
[TEST_T_UMI_FLEX.csv](https://github.com/user-attachments/files/15595292/TEST_T_UMI_FLEX.csv)

**Comment by dbenn** [comment]
Yes, I see. Thanks for picking this up. I see where in `ObservationSourceAnalyser` this is coming from. I'll look at this.

**Comment by dbenn** [comment]
<img width="628" alt="image" src="https://github.com/AAVSO/VStar/assets/4115628/0f637f85-d0da-41a2-ad08-e6acfab8d347">

**Comment by dbenn** [comment]
<img width="628" alt="image" src="https://github.com/AAVSO/VStar/assets/4115628/0f637f85-d0da-41a2-ad08-e6acfab8d347">
