### ISSUE TITLE
Error while creating VeLa model

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#429]
1) Open a light curve, for example, V965 Cep, Unfiltered with V zeropoint, from 2459945.5 to 2460309.5, ObsCode PMAK.
Convert to HJD (optional)
2) Create Fourier Model P=0.085067421, 6 harmonics (arbitrary)
3) Model -> Show Model -> Function. Copy function to clipboard.
4) Analysis -> VeLa model -> paste VelaCode.
4) Press OK. I see the following error:
![image](https://github.com/AAVSO/VStar/assets/44919945/3f926179-09a5-4e22-883b-bed62e222958)

**Comment by mpyat2** [comment]
Hi @dbenn 
Interestingly, this error does not come up in the "New star from VeLa model" observation source plug-in. Only in the VeLa Model tool plug-in.

**Comment by dbenn** [comment]
It relates to the observation environments being pushed in the model creator vs obs source.

**Comment by dbenn** [comment]
Note that running this (via `Run` button) in VeLa model dialog works fine:
~~~
zeroPoint is 48680

f(t:real) : real {
9.743964
+0.535862 * cos(2*PI*0.002295*(t-zeroPoint)) + 1.621261 * sin(2*PI*0.002295*(t-zeroPoint))
}

f(2447121.5)
~~~
Note that in this case there is the global `VeLaScope` and `f`'s `VeLaScope`, but no `VeLaValidObservationEnvironment` (a subclass of `VeLaScope`).

I'm about to commit:

- a UT that adds a `VeLaValidObservationEnvironment`
- a VeLaModel plugin test

They both work too, despite the presence of a `VeLaValidObservationEnvironment`.

**Comment by dbenn** [comment]
Commit message not specified properly on command-line, so repeated here:
~~~
now catching exception in VeLaValidObservationEnvironment.lookup()
~~~
https://github.com/AAVSO/VStar/commit/205cc043359ef206a02683859353983c6e202d55

**Comment by dbenn** [comment]
@mpyat2 I merged the pull request inadvertently. I can re-open this issue and create a new branch for any review rework if needed.

**Comment by dbenn** [comment]
@mpyat2 I see you approved the PR, thanks!
