### ISSUE TITLE
DCDFT calculates slightly distorted power values.

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#459]
TSBase.statcomp() is called several times (at least twice) while calculating DCDFT. Since the 'dvar' variable (magnitude variation) is never initialized explicitly, the 'dvar' value used for the power estimation is slightly distorted (see TSBase.project()).

Since we are interested in relative power values, this error does not affect the end user.

To resolve the issue, it is sufficient to initialize 'dvar' in TSBase.statcomp().

**Comment by dbenn** [comment]
Files to support Max's analysis: [files.zip](https://github.com/user-attachments/files/18138749/files.zip)

Thanks for the pick up and the analysis @mpyat2!

**Comment by dbenn** [comment]
I looked at the original Fortran code and can see that `dvar` is not initialised locally in `statcomp` either:
~~~
c local variables
      integer n,nx
      real*8 dw,dt,dx,dtspan,xx,dts2

      call setlimit

      nbrake=0
      numact=0
      dweight=0.d0
      dave=0.d0
      dtave=0.d0
      dtvar=0.d0
      do n=nlolim,nuplim
       if (wvec(n).gt.0.d0) then
        numact=numact+1
        dw=wvec(n)
        dt=tvec(n)
        dx=xvec(n)
        dweight=dweight+dw
        dave=dave + (dw*dx)
~~~
