### ISSUE TITLE
Harmonic search needs to use a numeric tolerance vs equality approach

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#62]
See findHarmonics() method in PeriodAnalysisDialogBase.

**Comment by dbenn** [comment]
@mdadighat I've been meaning to give an example of a method I've used in some of the unit test code for determining whether two values are close with respect to some tolerance (epsilon) value:
~~~
	private boolean areClose(double a, double b, double epsilon) {
		return Math.abs(a - b) < epsilon;
	}
~~~

**Comment by mdadighat** [comment]
@dbenn I originally was thinking something like that but then I went down a rabbit hole of attempting to account for significant figures and rounding and probably overcomplicated it. I had some issues with really small values (frequencies of .000711 and similar) but I don't know if that's part of the issue this is trying to solve.

**Comment by dbenn** [comment]
Hi @mdadighat I do completely understand about rabbit holes. I got down them on a regular basis. It's okay. In my experience, no solution is perfect. :) The question I would ask myself is whether some solution is better than what exists.
