### ISSUE TITLE
Zeros as defaults in HJD RA/Dec dialogs may be confusing

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#74]
Robert Jenkins has suggested that default zeros n HJD RA/Dec dialogs may be confusing, especially if they are not deleted and remain as leading zeros. I pointed out that this will have no impact, but I can see that it could be visually confusing.

**Comment by dbenn** [comment]
Looks like we can close this one too.

**Comment by mpyat2** [comment]
indeed
