### ISSUE TITLE
HJD conversion not visible immediately in observation list if that tab is selected at conversion time

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#76]
Robert Jenkins says:
> One thing that needs to be in the manual is that you need to do the HJD conversion when you have the “Plot” screen visible and then click on “Observations”.  If you are on the “Observations” screen when you do the conversions, nothing changes until you go to a different screen and return.

**Comment by mpyat2** [comment]
If Phase Plot is active, phases are not recalculated until the new Phase Plot is created. This should be taken into account.

**Comment by mpyat2** [comment]
see  issue-76-hjd-conv-not-visible-immediately branch
