### ISSUE TITLE
Architectural Plugin Fix

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#8]
### Architectural fix

- plugin/src/org/aavso/tools/vstar/external/plugin/ASASSNObservationSource.java
- plugin/src/org/aavso/tools/vstar/external/plugin/KeplerFITSObservationSource.java

In both plugins, parameter dialog moved from retrieveObservations() (where it is called in other than message queue thread) to getObservationRetriever(). This also prevents annoying “No observations for the specified period” error when the user presses [Cancel]

**Comment by dbenn** [comment]
Once @clkotnik is happy with the changes I'll merge them back to master.

**Comment by clkotnik** [comment]
Looks good to me
