### ISSUE TITLE
Possible memory leak from AbstractOkCancelDialog

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#9]
Possible memory leak?

src/org/aavso/tools/vstar/ui/dialog/AbstractOkCancelDialog.java

**this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE)**

I think it would be useful to prevent leaks, what do you think?

**Comment by mpyat2** [comment]
@dbenn : already fixed, can be closed
