### ISSUE TITLE
Make model equation term precisions consistent (use preferences)

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#92]
From https://sourceforge.net/p/vstar/bugs-and-features/591/

Fourier and polynomial models are not consistent.

This does still seem to be the case. Perhaps one uses Preferences and the other does not. What about Loess? Any others?

**Comment by mpyat2** [comment]
It's hard to make polynomial and Fourier coefficients fully precision consistent. The range of Fourier-model coefficients is relatively small; polynomial coefficients may vary by dozens of magnitude orders.
We could use "scientific" (%E) or "general" (%G) formatting for the polynomial coefficients and remain existing (decimal) formatting for the Fourier-model coefficients.
